In [1]:
from IPython.display import clear_output
from tools import memory

In [2]:
import torch
import torch.nn as nn
import numpy as np

clear_output()

In [5]:
import rnet 

In [10]:
array = np.array([1,2], dtype=np.float32)


test_weight = np.array([[1,2]
                        ,[3,4]], dtype=np.float32)

test_bias = np.array([1,2], dtype=np.float32)

 

In [7]:
my_linear_layer = rnet.Linear(in_features=2, out_features=2, is_bias=True)
torch_linear_layer =  nn.Linear(2, 2)

print(my_linear_layer)
print(torch_linear_layer)

Linear(in = 2,out = 2, params=6) 
Linear(in_features=2, out_features=2, bias=True)


In [8]:
print(f"""
origin wights :
{my_linear_layer.weight}
    ---------------------
{my_linear_layer.bias}

torch weights, bias:
{torch_linear_layer.weight.data}
{torch_linear_layer.bias.data}

""")


origin wights :
[[0.9744315  0.8054147 ]
 [0.8874335  0.23286068]]
    ---------------------
[0.51147157 0.11441487]

torch weights, bias:
tensor([[-0.2332, -0.6911],
        [-0.4209, -0.3538]])
tensor([-0.3860, -0.0862])




In [11]:
my_linear_layer.weight = test_weight
torch_linear_layer.weight = nn.Parameter(torch.tensor(test_weight, dtype=torch.float32))

my_linear_layer.bias = test_bias
torch_linear_layer.bias = nn.Parameter(torch.tensor(test_bias, dtype=torch.float32))


print(
    "my_linear_layer.weight: \n", my_linear_layer.weight, "\n",
    "torch_linear_layer.weight: \n", torch_linear_layer.weight, "\n\n",
    "my_linear_layer.bias: \n", my_linear_layer.bias, "\n",
    "torch_linear_layer.bias: \n", torch_linear_layer.bias, "\n",
)

my_linear_layer.weight: 
 [[1. 2.]
 [3. 4.]] 
 torch_linear_layer.weight: 
 Parameter containing:
tensor([[1., 2.],
        [3., 4.]], requires_grad=True) 

 my_linear_layer.bias: 
 [1. 2.] 
 torch_linear_layer.bias: 
 Parameter containing:
tensor([1., 2.], requires_grad=True) 



In [13]:
my_product = my_linear_layer(array)
torch_product = torch_linear_layer(torch.tensor(array, dtype=torch.float32))

print(
    f"Original product:\n {my_product},\n"
    f"PyTorch product:\n {torch_product}"
)

Original product:
 [ 6. 13.],
PyTorch product:
 tensor([ 6., 13.], grad_fn=<ViewBackward0>)


In [10]:
(array @ my_linear_layer.weight.T) + my_linear_layer.bias

array([ 6., 13.], dtype=float32)

In [11]:
( torch.tensor(array, dtype = torch.float32) @ torch_linear_layer.weight.detach().T) + nn.Parameter(torch_linear_layer.bias)

tensor([ 6., 13.], grad_fn=<AddBackward0>)

In [14]:
x = np.random.rand(20,3)
# y = np.random.randint(0,3,20)
y = np.random.randint(0,3,20)
# print(y)
y_c = np.eye(20,3)[y]
# print(y_c)

In [15]:
# from rnet import Linear, Neuaral
from tools import relu


class MySimpleNN(rnet.Neuaral):
    def __init__(self, input_size, output_size):
        super(MySimpleNN, self).__init__()
        self.fc1 = rnet.Linear(input_size, 100)  # First fully connected layer
        self.fc2 = rnet.Linear(100, output_size)  # Second fully connected layer
        pass

    def forward(self, x : np.ndarray):
        x = relu(self.fc1(x))  # Apply ReLU activation after the first layer
        x = self.fc2(x)  # Output layer
        return x

In [16]:
import torch
import torch.nn as nn
import torch.optim as optim
import torch.nn.functional as F
from torch.utils.data import DataLoader, TensorDataset

# Define the neural network model
class TorchSimpleNN(nn.Module):
    def __init__(self, input_size, output_size):
        super(TorchSimpleNN, self).__init__()
        self.fc1 = nn.Linear(input_size, 100)  # First fully connected layer
        self.fc2 = nn.Linear(100, output_size)  # Second fully connected layer

    def forward(self, x):
        x = F.relu(self.fc1(x))  # Apply ReLU activation after the first layer
        x = self.fc2(x)  # Output layer
        return x


# Initialize the model, loss function, and optimizer
# model = SimpleNN(input_size, hidden_size, output_size)
# criterion = nn.CrossEntropyLoss()
# optimizer = optim.SGD(model.parameters(), lr=0.01)

# # Training loop
# for epoch in range(100):  # Train for 100 epochs
#     for inputs, labels in dataloader:
#         # Forward pass
#         outputs = model(inputs)
#         loss = criterion(outputs, labels)
        
#         # Backward pass and optimization
#         optimizer.zero_grad()
#         loss.backward()
#         optimizer.step()

#     # Print loss every 10 epochs
#     if (epoch + 1) % 10 == 0:
#         print(f'Epoch [{epoch+1}/100], Loss: {loss.item():.4f}')

# # Example prediction
# with torch.no_grad():
#     example_input = torch.tensor([[0.5, -0.5]])
#     output = model(example_input)
#     predicted = torch.argmax(output, dim=1)
#     print(f'Predicted class: {predicted.item()}')


In [17]:
# Sample data (for demonstration purposes)
# Assuming input size is 2, output size is 2 (for binary classification)
input_size = 20
hidden_size = 50
output_size = 20

# Generate some random data
X = torch.randn(1000, input_size)  # 100 samples, 2 features each
y = torch.randint(0, output_size, (1000,))  # 100 labels (0 or 1)

# Create DataLoader
# dataset = TensorDataset(X, y)
# dataloader = DataLoader(dataset, batch_size=10, shuffle=True)

torch_model = TorchSimpleNN(input_size, output_size)
my_model = MySimpleNN(input_size, output_size)

In [18]:
@memory
def test_mine():
    # Test the mine function
    for i in range(10):
        for inputs, labels in zip(X,y):
            my_model(inputs)

@memory
def test_torch():
    # Test the mine function
    for i in range(10):
        for inputs, labels in zip(X,y):
            torch_model(inputs)


In [19]:
test_mine()

Memory usage of test_mine: 0.25 MB


In [20]:
test_torch()

Memory usage of test_torch: 0.14 MB
