In [1]:
from IPython.display import clear_output

In [2]:
import torch
import torch.nn as nn
import numpy as np

clear_output()

In [3]:
from rnet import rnet 

In [4]:
array = np.array([1,2], dtype=np.float32)


test_weight = np.array([[1,2]
                        ,[3,4]], dtype=np.float32)

test_bias = np.array([1,2], dtype=np.float32)

 

In [5]:
my_linear_layer = rnet.Linear(in_features=2, out_features=2, is_bias=True)
torch_linear_layer =  nn.Linear(2, 2)

In [6]:
print(f"""
origin wights :
{my_linear_layer.weight}
    ---------------------
{my_linear_layer.bias}

torch weights, bias:
{torch_linear_layer.weight.data}
{torch_linear_layer.bias.data}

""")


origin wights :
[[0.86793067 0.21336931]
 [0.83357403 0.1529093 ]]
    ---------------------
[0.52474148 0.1788682 ]

torch weights, bias:
tensor([[ 0.2964, -0.6877],
        [ 0.5105,  0.1474]])
tensor([ 0.1113, -0.5655])




In [7]:
my_linear_layer.weight = test_weight
torch_linear_layer.weight = nn.Parameter(torch.tensor(test_weight, dtype=torch.float32))

my_linear_layer.bias = test_bias
torch_linear_layer.bias = nn.Parameter(torch.tensor(test_bias, dtype=torch.float32))


print(
    "my_linear_layer.weight: \n", my_linear_layer.weight, "\n",
    "torch_linear_layer.weight: \n", torch_linear_layer.weight, "\n\n",
    "my_linear_layer.bias: \n", my_linear_layer.bias, "\n",
    "torch_linear_layer.bias: \n", torch_linear_layer.bias, "\n",
)

my_linear_layer.weight: 
 [[1. 2.]
 [3. 4.]] 
 torch_linear_layer.weight: 
 Parameter containing:
tensor([[1., 2.],
        [3., 4.]], requires_grad=True) 

 my_linear_layer.bias: 
 [1. 2.] 
 torch_linear_layer.bias: 
 Parameter containing:
tensor([1., 2.], requires_grad=True) 



In [8]:
my_linear_layer(array)

array([ 6., 13.], dtype=float32)

In [9]:
my_product = my_linear_layer(array)
torch_product = torch_linear_layer(torch.tensor(array, dtype=torch.float32))

print(
    f"Original product:\n {my_product},\n"
    f"PyTorch product:\n {torch_product}"
)

Original product:
 [ 6. 13.],
PyTorch product:
 tensor([ 6., 13.], grad_fn=<ViewBackward0>)


In [10]:
(array @ my_linear_layer.weight.T) + my_linear_layer.bias

array([ 6., 13.], dtype=float32)

In [11]:
( torch.tensor(array, dtype = torch.float32) @ torch_linear_layer.weight.detach().T) + nn.Parameter(torch_linear_layer.bias)

tensor([ 6., 13.], grad_fn=<AddBackward0>)